### ISSUE TITLE
Not working on python-chromedriver:3.6-selenium

### ISSUE THREAD

**Issue by arkkanoid** [joyzoursky/docker-python-chromedriver#2]
Hi, 
I'm trying your code but it's not working on this version:
joyzoursky/python-chromedriver:3.6-selenium

    >>> from selenium import webdriver
    >>> driver = webdriver.Chrome()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
        desired_capabilities=desired_capabilities)
      File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
        self.start_session(desired_capabilities, browser_profile)
      File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
        response = self.execute(Command.NEW_SESSION, parameters)
      File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
        self.error_handler.check_response(response)
      File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
        raise exception_class(message, screen, stacktrace)
    selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
      (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.9.60-linuxkit-aufs x86_64

**Comment by arkkanoid** [comment]
Solved:
chrome_options.add_argument('--no-sandbox')
